# Generated by Django 6.0.1 on 2026-01-11 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyberUser', '0004_alter_preferences_receive_newsletters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('base_sprite_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cybercreds_cost', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pet',
            },
        ),
        migrations.CreateModel(
            name='PetState',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50)),
                ('svg_url', models.CharField(blank=True, max_length=255, null=True)),
                ('animation_url', models.CharField(blank=True, max_length=255, null=True)),
                ('duration_ms', models.IntegerField(default=500)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='pets.pet')),
            ],
            options={
                'db_table': 'pet_state',
            },
        ),
        migrations.CreateModel(
            name='UserPet',
            fields=[
                ('user_pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='cyberUser.cyberuser')),
            ],
            options={
                'db_table': 'user_pet',
                'unique_together': {('user', 'pet')},
            },
        ),
    ]
