# Generated by Django 6.0.1 on 2026-01-11 13:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='base_sprite_url',
        ),
        migrations.RemoveField(
            model_name='petstate',
            name='svg_url',
        ),
        migrations.AddField(
            model_name='pet',
            name='base_sprite',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='petstate',
            name='svg',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='svg'),
        ),
        migrations.AlterField(
            model_name='petstate',
            name='animation_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='animation'),
        ),
    ]
