# Generated by Django 6.0.1 on 2026-01-11 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyberUser', '0006_alter_cyberuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('minigame_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_points', models.IntegerField(default=50)),
                ('time_limit_sec', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'minigame',
            },
        ),
        migrations.CreateModel(
            name='MinigameSession',
            fields=[
                ('minigame_session_id', models.AutoField(primary_key=True, serialize=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('incorrect_answers', models.IntegerField(default=0)),
                ('time_spent_sec', models.IntegerField(blank=True, null=True)),
                ('minigame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='minigames.minigame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minigame_sessions', to='cyberUser.cyberuser')),
            ],
            options={
                'db_table': 'minigame_session',
            },
        ),
        migrations.CreateModel(
            name='SwipeQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_content', models.TextField()),
                ('correct_answer', models.CharField(max_length=20)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.IntegerField(default=1)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swipe_questions', to='cyberUser.country')),
                ('minigame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='minigames.minigame')),
            ],
            options={
                'db_table': 'swipe_question',
            },
        ),
        migrations.CreateModel(
            name='SwipeResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_answer', models.CharField(max_length=20)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('minigame_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='minigames.minigamesession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='minigames.swipequestion')),
            ],
            options={
                'db_table': 'swipe_response',
            },
        ),
    ]
