# Generated by Django 4.2.27 on 2026-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyberuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='cyberuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='cyberuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='cyberuser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='cyberuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyberuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
