# Generated by Django 6.0.1 on 2026-01-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0002_remove_cyberuser_groups_remove_cyberuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('receive_newsletters', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'preferences',
            },
        ),
        migrations.AddField(
            model_name='cyberuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='cyberuser',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cyberUser.preferences'),
        ),
    ]
