# Generated by Django 6.0.1 on 2026-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0003_preferences_cyberuser_avatar_cyberuser_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='receive_newsletters',
            field=models.BooleanField(default=False),
        ),
    ]
