# Generated by Django 6.0.1 on 2026-01-11 13:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0004_alter_preferences_receive_newsletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
