# Generated by Django 6.0.1 on 2026-01-11 15:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0005_alter_cyberuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, default='avatars/default.jpg', max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
