# Generated by Django 6.0.1 on 2026-01-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0006_alter_cyberuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='base_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preferences',
            name='tone_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
