# Generated by Django 6.0.1 on 2026-01-14 01:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cyberUser", "0007_preferences_age_preferences_base_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cyberuser",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                default=1, max_length=255, verbose_name="avatar"
            ),
            preserve_default=False,
        ),
    ]
