# Generated by Django 6.0.1 on 2026-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0008_alter_cyberuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferences',
            name='background_music_volume',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='preferences',
            name='pet_tts_volume',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='preferences',
            name='sfx_volume',
            field=models.FloatField(default=0.5),
        ),
    ]
