# Generated by Django 6.0.1 on 2026-02-16 14:57

import django.core.validators
from django.db import migrations, models


def clamp_volumes(apps, schema_editor):
    Preferences = apps.get_model('cyberUser', 'Preferences')

    def clamp01(value, default):
        if value is None:
            return default
        try:
            value = float(value)
        except Exception:
            return default
        if value < 0.0:
            return 0.0
        if value > 1.0:
            return 1.0
        return value

    for prefs in Preferences.objects.all().iterator():
        new_bg = clamp01(getattr(prefs, 'background_music_volume', None), 0.3)
        new_sfx = clamp01(getattr(prefs, 'sfx_volume', None), 0.5)
        new_tts = clamp01(getattr(prefs, 'pet_tts_volume', None), 1.0)

        updates = {}
        if prefs.background_music_volume != new_bg:
            updates['background_music_volume'] = new_bg
        if prefs.sfx_volume != new_sfx:
            updates['sfx_volume'] = new_sfx
        if prefs.pet_tts_volume != new_tts:
            updates['pet_tts_volume'] = new_tts

        if updates:
            Preferences.objects.filter(pk=prefs.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0009_preferences_background_music_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='background_music_volume',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='pet_tts_volume',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='sfx_volume',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.RunPython(clamp_volumes, migrations.RunPython.noop),
    ]
