# Generated by Django 6.0.1 on 2026-01-10 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyberUser', '0002_remove_cyberuser_groups_remove_cyberuser_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido de la pregunta')),
                ('response_type', models.CharField(choices=[('multiple_choice', 'Opción Múltiple'), ('yes_no', 'Sí/No'), ('scale', 'Escala')], max_length=50, verbose_name='Tipo de respuesta')),
                ('risk_weight', models.IntegerField(default=1, help_text='Multiplicador para calcular el nivel de riesgo', verbose_name='Peso de riesgo')),
                ('display_order', models.IntegerField(verbose_name='Orden de visualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Pregunta de Onboarding',
                'verbose_name_plural': 'Preguntas de Onboarding',
                'db_table': 'onboarding_question',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='Contenido de la opción')),
                ('risk_value', models.IntegerField(help_text='0=bajo riesgo, 5=alto riesgo', verbose_name='Valor de riesgo')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='Orden de visualización')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='onboarding.onboardingquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'db_table': 'answer_option',
                'ordering': ['question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='GlobalStatistic',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=100, verbose_name='Métrica')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado en')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='cyberUser.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Estadística Global',
                'verbose_name_plural': 'Estadísticas Globales',
                'db_table': 'global_statistic',
                'indexes': [models.Index(fields=['metric', 'country'], name='global_stat_metric_708549_idx')],
            },
        ),
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('open_answer', models.TextField(blank=True, null=True, verbose_name='Respuesta abierta')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='onboarding.answeroption', verbose_name='Opción seleccionada')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='onboarding.onboardingquestion', verbose_name='Pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to='cyberUser.cyberuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Respuesta de Onboarding',
                'verbose_name_plural': 'Respuestas de Onboarding',
                'db_table': 'onboarding_response',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric', models.CharField(help_text='Ej: success_rate, avg_time, total_points', max_length=100, verbose_name='Métrica')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Calculado en')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='cyberUser.cyberuser', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estadística de Usuario',
                'verbose_name_plural': 'Estadísticas de Usuario',
                'db_table': 'user_statistic',
                'indexes': [models.Index(fields=['user', 'metric'], name='user_statis_user_id_568662_idx')],
            },
        ),
    ]
