# Generated by Django 6.0.1 on 2026-01-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0003_preferences_cyberuser_avatar_cyberuser_preferences'),
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answeroption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='globalstatistic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='onboardingquestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='onboardingresponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userstatistic',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='globalstatistic',
            name='global_stat_metric_708549_idx',
        ),
        migrations.RemoveIndex(
            model_name='userstatistic',
            name='user_statis_user_id_568662_idx',
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='display_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='onboarding.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='risk_value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='globalstatistic',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='globalstatistic',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='cyberUser.country'),
        ),
        migrations.AlterField(
            model_name='globalstatistic',
            name='metric',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='globalstatistic',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='display_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='response_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='onboardingquestion',
            name='risk_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='open_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='onboarding.answeroption'),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='onboarding.onboardingquestion'),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='onboardingresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_responses', to='cyberUser.cyberuser'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='metric',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='cyberUser.cyberuser'),
        ),
        migrations.AlterField(
            model_name='userstatistic',
            name='value',
            field=models.FloatField(),
        ),
    ]
