# Generated by Copilot on 2026-02-14

from django.db import migrations
from django.db.models import Max


def add_age_question(apps, schema_editor):
    OnboardingQuestion = apps.get_model('onboarding', 'OnboardingQuestion')

    content = '¿Cuántos años tienes?'

    # Evitar duplicados si ya existe una pregunta similar
    existing = OnboardingQuestion.objects.filter(content=content).first()
    if existing:
        # Asegurar que esté activa y con el tipo correcto
        updates = {}
        if existing.response_type != 'age':
            updates['response_type'] = 'age'
        if existing.risk_weight != 0:
            updates['risk_weight'] = 0
        if existing.is_active is not True:
            updates['is_active'] = True
        if updates:
            OnboardingQuestion.objects.filter(pk=existing.pk).update(**updates)
        return

    max_order = OnboardingQuestion.objects.aggregate(Max('display_order')).get('display_order__max')
    next_order = (max_order or 0) + 1

    OnboardingQuestion.objects.create(
        content=content,
        response_type='age',
        risk_weight=0,
        display_order=next_order,
        is_active=True,
    )


def remove_age_question(apps, schema_editor):
    OnboardingQuestion = apps.get_model('onboarding', 'OnboardingQuestion')
    OnboardingQuestion.objects.filter(content='¿Cuántos años tienes?').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_alter_answeroption_options_and_more'),
    ]

    operations = [
        migrations.RunPython(add_age_question, remove_age_question),
    ]
