# Generated by Django 6.0.1 on 2026-01-11 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cyberUser', '0007_preferences_age_preferences_base_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=255, null=True)),
                ('cybercreds_cost', models.IntegerField()),
                ('required_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cosmetic_item',
            },
        ),
        migrations.CreateModel(
            name='ProgressionLevel',
            fields=[
                ('level_id', models.AutoField(primary_key=True, serialize=False)),
                ('level_number', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('required_xp', models.IntegerField()),
                ('cybercreds_reward', models.IntegerField(default=0)),
                ('badge_url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'progression_level',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cyberUser.cyberuser')),
            ],
            options={
                'db_table': 'credit_transaction',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_xp', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='progression.progressionlevel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='cyberUser.cyberuser')),
            ],
            options={
                'db_table': 'user_progress',
            },
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='progression.cosmeticitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='cyberUser.cyberuser')),
            ],
            options={
                'db_table': 'user_inventory',
                'unique_together': {('user', 'item')},
            },
        ),
    ]
