# Generated by Django 6.0.1 on 2026-02-21 11:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberUser', '0010_alter_preferences_background_music_volume_and_more'),
        ('progression', '0002_remove_cosmeticitem_preview_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('quiz', 'Quiz'), ('simulation', 'Simulación'), ('progression', 'Progresión'), ('social', 'Social'), ('collection', 'Colección')], default='progression', max_length=50)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
                ('cybercreds_reward', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=0)),
                ('requirement_type', models.CharField(max_length=50)),
                ('requirement_value', models.IntegerField(default=1)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('user_achievement_id', models.AutoField(primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0)),
                ('is_claimed', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_achieved', to='progression.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='cyberUser.cyberuser')),
            ],
            options={
                'db_table': 'user_achievement',
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
