# Generated by Django 6.0.1 on 2026-02-11 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberUser", "0008_alter_cyberuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "risk_category",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AudienceSegment",
            fields=[
                ("segment_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("min_age", models.IntegerField()),
                ("max_age", models.IntegerField()),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "audience_segment",
                "ordering": ["display_order", "min_age"],
                "indexes": [
                    models.Index(
                        fields=["min_age", "max_age"],
                        name="audience_se_min_age_c40e0a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("quiz_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("difficulty_level", models.IntegerField(default=1)),
                ("base_points", models.IntegerField(default=100)),
                ("time_limit_seconds", models.IntegerField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="quiz.audiencesegment",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="quiz.riskcategory",
                    ),
                ),
            ],
            options={
                "db_table": "quiz",
                "ordering": ["segment", "category", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("explanation", models.TextField(blank=True, null=True)),
                ("points", models.IntegerField(default=10)),
                ("display_order", models.IntegerField()),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quiz",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_question",
                "ordering": ["quiz", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuizHint",
            fields=[
                ("hint_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("cost_points", models.IntegerField(default=5)),
                ("display_order", models.IntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="quiz.quizquestion",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_hint",
                "ordering": ["question", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAlternative",
            fields=[
                ("alternative_id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("feedback", models.TextField()),
                ("display_order", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternatives",
                        to="quiz.quizquestion",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_alternative",
                "ordering": ["question", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("points_earned", models.IntegerField(default=0)),
                ("hints_used", models.IntegerField(default=0)),
                ("status", models.CharField(default="in_progress", max_length=20)),
                ("time_spent_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_sessions",
                        to="cyberUser.cyberuser",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                ("answer_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_correct", models.BooleanField()),
                ("hints_used_count", models.IntegerField(default=0)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                ("time_spent_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "selected_alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizalternative",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.quizsession",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_answer",
                "ordering": ["session", "answered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["quiz", "display_order"], name="quiz_questi_quiz_id_d40d2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizhint",
            index=models.Index(
                fields=["question", "display_order"],
                name="quiz_hint_questio_32f411_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizalternative",
            index=models.Index(
                fields=["question", "display_order"],
                name="quiz_altern_questio_c89074_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quizsession",
            index=models.Index(
                fields=["user", "quiz"], name="quiz_sessio_user_id_e10711_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizsession",
            index=models.Index(
                fields=["started_at"], name="quiz_sessio_started_dbe942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizanswer",
            index=models.Index(
                fields=["session", "question"], name="quiz_answer_session_3eb484_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["segment", "category", "is_active"],
                name="quiz_segment_a1a67c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["display_order"], name="quiz_display_172c61_idx"
            ),
        ),
    ]
