# Generated by Django 6.0.1 on 2026-02-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="quizzes/"),
        ),
    ]
