# Generated by Django 6.0.1 on 2026-02-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quiz_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="attempt_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="coins_earned",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="total_answered",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quizsession",
            name="total_correct",
            field=models.IntegerField(default=0),
        ),
    ]
