# Generated by Django 6.0.1 on 2026-02-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quizsession_attempt_number_quizsession_coins_earned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizsession",
            name="status",
            field=models.CharField(
                choices=[("not_started", "No iniciado"), ("completed", "Realizado")],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
