# Generated by Django 6.0.1 on 2026-01-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cyberUser", "0008_alter_cyberuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                ("scenario_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("antagonist_goal", models.CharField(max_length=100)),
                ("difficulty_level", models.IntegerField()),
                ("base_points", models.IntegerField(default=100)),
                ("threat_type", models.CharField(blank=True, max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "scenario",
            },
        ),
        migrations.CreateModel(
            name="SensitivePattern",
            fields=[
                ("pattern_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("regex_pattern", models.CharField(max_length=500)),
                ("data_type", models.CharField(max_length=50)),
                (
                    "alert_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("severity", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "sensitive_pattern",
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="in_progress", max_length=20)),
                ("points_earned", models.IntegerField(default=0)),
                ("is_game_over", models.BooleanField(default=False)),
                (
                    "game_over_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_sessions",
                        to="cyberUser.cyberuser",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="simulation.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "game_session",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("message_id", models.AutoField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("is_dangerous", models.BooleanField(default=False)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="simulation.gamesession",
                    ),
                ),
                (
                    "detected_pattern",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="simulation.sensitivepattern",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
            },
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(fields=["user"], name="game_sessio_user_id_0500e0_idx"),
        ),
        migrations.AddIndex(
            model_name="gamesession",
            index=models.Index(
                fields=["started_at"], name="game_sessio_started_83440d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session"], name="chat_messag_session_389d44_idx"
            ),
        ),
    ]
