# Generated by Django 6.0.1 on 2026-01-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="antagonist_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="outcome",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="points_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="scenario_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="is_game_over",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
