# Generated by Django 6.0.1 on 2026-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "simulation",
            "0002_gamesession_antagonist_attempts_gamesession_outcome_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamesession",
            name="game_over_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
